// <auto-generated />
using System;
using BusinessMaster.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessMaster.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20210813080914_ScriptA")]
    partial class ScriptA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessMaster.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientAge")
                        .HasColumnType("int");

                    b.Property<int>("ClientBudget")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServicesNameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDeliveryDate")
                        .HasColumnType("date");

                    b.HasKey("ClientId");

                    b.HasIndex("ServicesNameId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("BusinessMaster.Models.ServicesName", b =>
                {
                    b.Property<int>("ServicesNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServicesNameId");

                    b.ToTable("servicesNames");
                });

            modelBuilder.Entity("BusinessMaster.Models.Client", b =>
                {
                    b.HasOne("BusinessMaster.Models.ServicesName", "ServicesName")
                        .WithMany("Client")
                        .HasForeignKey("ServicesNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicesName");
                });

            modelBuilder.Entity("BusinessMaster.Models.ServicesName", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
